import { Router } from 'express';
import { createAuthModule } from '../modules/auth/index.js';
import { createCandidateManagementModule } from '../modules/candidate-management/index.js';
import { screeningPipelineRouter } from '../modules/screening-pipeline/index.js';
import { createFormBuilderModule } from '../modules/form-builder/index.js';
import { createUserManagementModule } from '../modules/user-management/index.js';
import { createOrgManagementModule } from '../modules/org-management/index.js';
import appAuthRoutes from './app-auth.routes.js';
import appApplicationIntakeRoutes from './app-application-intake.routes.js';
import appConsentRoutes from './app-consent.routes.js';
import appProfileRoutes from './app-profile.routes.js';
import stateStoreRoutes from './state-store.routes.js';
import shellRoutes from './shell.routes.js';
import firebaseRoutes from './firebase.routes.js';
import notificationRoutes from './notification.routes.js';
import localizationRoutes from './localization.routes.js';
import oauthRoutes from './oauth.routes.js';
import mockRoutes from './mock.routes.js';
import themeRoutes from './theme.routes.js';
import uiKitRoutes from './ui-kit.routes.js';
// user-management routes replaced by Clean Architecture module
// org-management routes replaced by Clean Architecture module
import accountSettingsRoutes from './account-settings.routes.js';
import jobRoutes from './job.routes.js';
import exportRoutes from './export.routes.js';
import viewComponentsRoutes from './view-components.routes.js';
// form-builder routes replaced by Clean Architecture module
import fileManagementRoutes from './file-management.routes.js';
import assetManagementRoutes from './asset-management.routes.js';
import chatRoutes from './chat.routes.js';
import chartingRoutes from './charting.routes.js';
import billingLedgerRoutes from './billing-ledger.routes.js';
import homeDashboardRoutes from './home-dashboard.routes.js';
import sharedWidgetsRoutes from './shared-widgets.routes.js';
import templateLayoutsRoutes from './template-layouts.routes.js';
import consentRoutes from './consent.routes.js';
import applicationRoutes from './application.routes.js';
import globalCandidateIdentityRoutes from './global-candidate-identity.routes.js';
import clientPortalRoutes from './client-portal.routes.js';
import customComponentsRoutes from './custom-components.routes.js';
import webhookRoutes from './webhook.routes.js';
import reviewTaskRoutes from './review-task.routes.js';

// Initialize Clean Architecture modules
const authModule = createAuthModule();
const candidateManagementModule = createCandidateManagementModule();
const formBuilderModule = createFormBuilderModule();
const userManagementModule = createUserManagementModule();
const orgManagementModule = createOrgManagementModule();

const router = Router();

router.use('/auth', authModule.routes);
router.use('/app/auth', appAuthRoutes);
router.use('/app/applications', appApplicationIntakeRoutes);
router.use('/app/consent', appConsentRoutes);
router.use('/app/profile', appProfileRoutes);
router.use('/state', stateStoreRoutes);
router.use('/shell', shellRoutes);
router.use('/firebase', firebaseRoutes);
router.use('/notifications', notificationRoutes);
router.use('/localization', localizationRoutes);
router.use('/oauth', oauthRoutes);
router.use('/mock', mockRoutes);
router.use('/theme', themeRoutes);
router.use('/ui-kit', uiKitRoutes);
router.use('/users', userManagementModule.routes);
router.use('/organizations', orgManagementModule.routes);
router.use('/account', accountSettingsRoutes);
router.use('/jobs', jobRoutes);
router.use('/exports', exportRoutes);
router.use('/view-components', viewComponentsRoutes);
router.use('/candidates', candidateManagementModule.routes);
router.use('/forms', formBuilderModule.routes);
router.use('/files', fileManagementRoutes);
router.use('/assets', assetManagementRoutes);
router.use('/chat', chatRoutes);
router.use('/charts', chartingRoutes);
router.use('/', billingLedgerRoutes);
router.use('/dashboard', homeDashboardRoutes);
router.use('/widgets', sharedWidgetsRoutes);
router.use('/template-layouts', templateLayoutsRoutes);
router.use('/consent', consentRoutes);
router.use('/applications', applicationRoutes);
router.use('/screening-pipelines', screeningPipelineRouter);
router.use('/global-candidates', globalCandidateIdentityRoutes);
router.use('/client', clientPortalRoutes);
router.use('/components', customComponentsRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/reviews', reviewTaskRoutes);

export default router;
