import { Router } from 'express';
// ── Clean Architecture module imports ────────────────────────────────────────
import { createAuthModule } from '../modules/auth/index.js';
import { createCandidateManagementModule } from '../modules/candidate-management/index.js';
import { screeningPipelineRouter } from '../modules/screening-pipeline/index.js';
import { createFormBuilderModule } from '../modules/form-builder/index.js';
import { createUserManagementModule } from '../modules/user-management/index.js';
import { createOrgManagementModule } from '../modules/org-management/index.js';
import { createChatModule } from '../modules/chat/index.js';
import { createNotificationModule } from '../modules/notification/index.js';
import { createFileManagementModule } from '../modules/file-management/index.js';
import { createBillingLedgerModule } from '../modules/billing-ledger/index.js';
import { createAssetManagementModule } from '../modules/asset-management/index.js';
import { createClientPortalModule } from '../modules/client-portal/index.js';
import { createHomeDashboardModule } from '../modules/home-dashboard/index.js';
import { createTemplateLayoutsModule } from '../modules/template-layouts/index.js';
import { createThemeModule } from '../modules/theme/index.js';
import { createLocalizationModule } from '../modules/localization/index.js';
import { createOAuthModule } from '../modules/oauth/index.js';
import { createStateStoreModule } from '../modules/state-store/index.js';
import { createCustomComponentsModule } from '../modules/custom-components/index.js';
import { createShellModule } from '../modules/shell/index.js';
import { createFirebaseModule } from '../modules/firebase/index.js';
import { createMockModule } from '../modules/mock/index.js';
import { createWebhookModule } from '../modules/webhook/index.js';
import { createReviewTaskModule } from '../modules/review-task/index.js';
import { createUIKitModule } from '../modules/ui-kit/index.js';
import { createAccountSettingsModule } from '../modules/account-settings/index.js';
import { createJobModule } from '../modules/job/index.js';
import { createExportModule } from '../modules/export/index.js';
import { createViewComponentsModule } from '../modules/view-components/index.js';
import { createChartingModule } from '../modules/charting/index.js';
import { createSharedWidgetsModule } from '../modules/shared-widgets/index.js';
import { createConsentModule } from '../modules/consent/index.js';
import { createApplicationModule } from '../modules/application/index.js';
import { createGlobalCandidateIdentityModule } from '../modules/global-candidate-identity/index.js';
import { createAppAuthModule } from '../modules/app-auth/index.js';
import { createAppApplicationIntakeModule } from '../modules/app-application-intake/index.js';
import { createAppConsentModule } from '../modules/app-consent/index.js';
import { createAppProfileModule } from '../modules/app-profile/index.js';
// Legacy app route imports replaced by Clean Architecture modules

// ── Initialize Clean Architecture modules ────────────────────────────────────
const authModule = createAuthModule();
const candidateManagementModule = createCandidateManagementModule();
const formBuilderModule = createFormBuilderModule();
const userManagementModule = createUserManagementModule();
const orgManagementModule = createOrgManagementModule();
const chatModule = createChatModule();
const notificationModule = createNotificationModule();
const fileManagementModule = createFileManagementModule();
const billingLedgerModule = createBillingLedgerModule();
const assetManagementModule = createAssetManagementModule();
const clientPortalModule = createClientPortalModule();
const homeDashboardModule = createHomeDashboardModule();
const templateLayoutsModule = createTemplateLayoutsModule();
const themeModule = createThemeModule();
const localizationModule = createLocalizationModule();
const oauthModule = createOAuthModule();
const stateStoreModule = createStateStoreModule();
const customComponentsModule = createCustomComponentsModule();
const shellModule = createShellModule();
const firebaseModule = createFirebaseModule();
const mockModule = createMockModule();
const webhookModule = createWebhookModule();
const reviewTaskModule = createReviewTaskModule();
const uiKitModule = createUIKitModule();
const accountSettingsModule = createAccountSettingsModule();
const jobModule = createJobModule();
const exportModule = createExportModule();
const viewComponentsModule = createViewComponentsModule();
const chartingModule = createChartingModule();
const sharedWidgetsModule = createSharedWidgetsModule();
const consentModule = createConsentModule();
const applicationModule = createApplicationModule();
const globalCandidateIdentityModule = createGlobalCandidateIdentityModule();
const appAuthModule = createAppAuthModule();
const appApplicationIntakeModule = createAppApplicationIntakeModule();
const appConsentModule = createAppConsentModule();
const appProfileModule = createAppProfileModule();

const router = Router();

// ── Clean Architecture module routes ─────────────────────────────────────────
router.use('/auth', authModule.routes);
router.use('/app/auth', appAuthModule.router);
router.use('/app/applications', appApplicationIntakeModule.router);
router.use('/app/consent', appConsentModule.router);
router.use('/app/profile', appProfileModule.router);
router.use('/state', stateStoreModule.router);
router.use('/shell', shellModule.router);
router.use('/firebase', firebaseModule.router);
router.use('/notifications', notificationModule.routes);
router.use('/localization', localizationModule.router);
router.use('/oauth', oauthModule.router);
router.use('/mock', mockModule.router);
router.use('/theme', themeModule.router);
router.use('/ui-kit', uiKitModule.router);
router.use('/users', userManagementModule.routes);
router.use('/organizations', orgManagementModule.routes);
router.use('/account', accountSettingsModule.router);
router.use('/jobs', jobModule.router);
router.use('/exports', exportModule.router);
router.use('/view-components', viewComponentsModule.router);
router.use('/candidates', candidateManagementModule.routes);
router.use('/forms', formBuilderModule.routes);
router.use('/files', fileManagementModule.routes);
router.use('/assets', assetManagementModule.router);
router.use('/chat', chatModule.routes);
router.use('/charts', chartingModule.router);
router.use('/', billingLedgerModule.routes);
router.use('/dashboard', homeDashboardModule.router);
router.use('/widgets', sharedWidgetsModule.router);
router.use('/template-layouts', templateLayoutsModule.router);
router.use('/consent', consentModule.router);
router.use('/applications', applicationModule.router);
router.use('/screening-pipelines', screeningPipelineRouter);
router.use('/global-candidates', globalCandidateIdentityModule.router);
router.use('/client', clientPortalModule.router);
router.use('/components', customComponentsModule.router);
router.use('/webhooks', webhookModule.router);
router.use('/reviews', reviewTaskModule.router);

export default router;
