import { Router } from 'express';
import authRoutes from './auth.routes.js';
import appAuthRoutes from './app-auth.routes.js';
import stateStoreRoutes from './state-store.routes.js';
import shellRoutes from './shell.routes.js';
import firebaseRoutes from './firebase.routes.js';
import notificationRoutes from './notification.routes.js';
import localizationRoutes from './localization.routes.js';
import oauthRoutes from './oauth.routes.js';
import mockRoutes from './mock.routes.js';
import themeRoutes from './theme.routes.js';
import uiKitRoutes from './ui-kit.routes.js';
import userManagementRoutes from './user-management.routes.js';
import orgManagementRoutes from './org-management.routes.js';
import accountSettingsRoutes from './account-settings.routes.js';
import jobRoutes from './job.routes.js';
import exportRoutes from './export.routes.js';
import viewComponentsRoutes from './view-components.routes.js';
import candidateManagementRoutes from './candidate-management.routes.js';
import formBuilderRoutes from './form-builder.routes.js';
import fileManagementRoutes from './file-management.routes.js';
import assetManagementRoutes from './asset-management.routes.js';
import chatRoutes from './chat.routes.js';
import chartingRoutes from './charting.routes.js';
import billingLedgerRoutes from './billing-ledger.routes.js';
import homeDashboardRoutes from './home-dashboard.routes.js';
import sharedWidgetsRoutes from './shared-widgets.routes.js';
import templateLayoutsRoutes from './template-layouts.routes.js';
import consentRoutes from './consent.routes.js';
import applicationRoutes from './application.routes.js';
import screeningPipelineRoutes from './screening-pipeline.routes.js';
import globalCandidateIdentityRoutes from './global-candidate-identity.routes.js';
import clientPortalRoutes from './client-portal.routes.js';
import customComponentsRoutes from './custom-components.routes.js';
import webhookRoutes from './webhook.routes.js';
import reviewTaskRoutes from './review-task.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/app/auth', appAuthRoutes);
router.use('/state', stateStoreRoutes);
router.use('/shell', shellRoutes);
router.use('/firebase', firebaseRoutes);
router.use('/notifications', notificationRoutes);
router.use('/localization', localizationRoutes);
router.use('/oauth', oauthRoutes);
router.use('/mock', mockRoutes);
router.use('/theme', themeRoutes);
router.use('/ui-kit', uiKitRoutes);
router.use('/users', userManagementRoutes);
router.use('/organizations', orgManagementRoutes);
router.use('/account', accountSettingsRoutes);
router.use('/jobs', jobRoutes);
router.use('/exports', exportRoutes);
router.use('/view-components', viewComponentsRoutes);
router.use('/candidates', candidateManagementRoutes);
router.use('/forms', formBuilderRoutes);
router.use('/files', fileManagementRoutes);
router.use('/assets', assetManagementRoutes);
router.use('/chat', chatRoutes);
router.use('/charts', chartingRoutes);
router.use('/', billingLedgerRoutes);
router.use('/dashboard', homeDashboardRoutes);
router.use('/widgets', sharedWidgetsRoutes);
router.use('/template-layouts', templateLayoutsRoutes);
router.use('/consent', consentRoutes);
router.use('/applications', applicationRoutes);
router.use('/screening-pipelines', screeningPipelineRoutes);
router.use('/global-candidates', globalCandidateIdentityRoutes);
router.use('/client', clientPortalRoutes);
router.use('/components', customComponentsRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/reviews', reviewTaskRoutes);

export default router;
